kind: Deployment
apiVersion: apps/v1
metadata:
  name: submariner-addon
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: submariner-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submariner-addon
  template:
    metadata:
      labels:
        app: submariner-addon
    spec:
      serviceAccountName: submariner-addon-sa
      containers:
      - name: submariner-addon
        image: {{ .Image }}
    {{- with .ResourceRequirements }}
      {{- $matchedIndex := -1 }}
      {{- range $index, $item := . }}
        {{- if regexMatch $item.ContainerIDRegex "deployments:submariner-addon:submariner-addon" }}
          {{- $matchedIndex = $index }}
        {{- end }}
      {{- end }}
      {{- if ne $matchedIndex -1 }}
        {{- $matched := index . $matchedIndex }}
        resources:
        {{- if $matched.Resources.Requests }}
          requests:
          {{- range $key, $value := $matched.Resources.Requests }}
            "{{ $key }}": "{{ $value }}"
          {{- end }}
        {{- end }}
        {{- if $matched.Resources.Limits }}
          limits:
          {{- range $key, $value := $matched.Resources.Limits }}
            "{{ $key }}": "{{ $value }}"
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
        env:
        - name: HUB_HOST
          value: "{{ .HubHost }}"
        {{- if .OpenShiftProfile }}
        - name: OPENSHIFT_PROFILE
          value: "{{ .OpenShiftProfile }}"
          {{- if .OpenShiftProfileHost }}
        - name: OPENSHIFT_PROFILE_HOST
          value: "{{ .OpenShiftProfileHost }}"
          {{- end }}
          {{- if .OpenShiftProfilePort }}
        - name: OPENSHIFT_PROFILE_PORT
          value: "{{ .OpenShiftProfilePort }}"
          {{- end }}
        {{- end }}
        args:
          - "/submariner"
          - "agent"
          - "--hub-kubeconfig=/var/run/hub/kubeconfig"
          - "--cluster-name={{ .ClusterName }}"
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub
          - name: tmp
            mountPath: /tmp
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .HubKubeConfigSecret }}
      - name: tmp
        emptyDir: {}
      {{- if .NodeSelector }}
      nodeSelector:
      {{- range $key, $value := .NodeSelector }}
        "{{ $key }}": "{{ $value }}"
      {{- end }}
      {{- end }}
      {{- if .Tolerations }}
      tolerations:
      {{- range $toleration := .Tolerations }}
      {{- if $toleration.Key }}
      - key: "{{ $toleration.Key }}"
      {{- if $toleration.Operator }}
        operator: "{{ $toleration.Operator }}"
      {{- end }}
      {{- else }}
      - operator: "{{ $toleration.Operator }}"
      {{- end }}
      {{- if $toleration.Value }}
        value: "{{ $toleration.Value }}"
      {{- end }}
      {{- if $toleration.Effect }}
        effect: "{{ $toleration.Effect }}"
      {{- end }}
      {{- if $toleration.TolerationSeconds }}
        tolerationSeconds: {{ $toleration.TolerationSeconds }}
      {{- end }}
      {{- end }}
      {{- end }}

